### ISSUE TITLE
ZipLoader import fixes for sublime_plugin.py in presence of a .sublime-package

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/Packages#75]
I investigated into https://github.com/SublimeTextIssues/Core/issues/935 and fixed it, while also fixing an issue with modules remaining in `sys.modules` even if the import failed, which I discovered in the process.

For the cause of the bug, please read my (lengthy) comment at https://github.com/SublimeTextIssues/Core/issues/935#issuecomment-122144515.

I figured this was the best place to suggest this patch, even though the repo only contains "non-core packages".

### Changes

1. Create empty parent packages if no `__init__.py` exists in an override package that didn't exist in the zipfile.
2. Refactored code a bit to more easily catch any exception when loading a module and remove the module from `sys.modules` if something went wrong. Remove only if the module wasn't there previously however. See [the blockquote section of PEP 0302, specification part 1](https://www.python.org/dev/peps/pep-0302/#specification-part-1-the-importer-protocol).

### Other Remarks

1. self.contents and self.packages are initialized with a few empty string because the ZipLoader is also triggered for the very base module, which is just the package name, and the "key lookup" resolves to looking for the empty string. This looks ugly at first sight, but is required to override the base-package's contents with the contents of `__init__.py`. Problem: This only happens if `__init__.py` is overidden (and exists as a file) but not if it is included in the zipfile, since it is explicitly excluded from that case.

2. Even though `__init__.py` is loaded by normal Python import mechanics already, most notably if a zipfile does not exist, it is still considered a plugin interfacing file and loaded *again* from `sublime_plugin.reload_module`. This causes `__init__.py` to be run twice, iff a `.sublime-package` does not exist or it exists and `__init__.py` is overridden.
   Interestingly, `__path__` is not set when `__init__ .py` is loaded a second ot n-th time via `sublime_plugin.reload_module` and causes a NameError.
   Example code:

   ```py
   print("we loaded with", __loader__)
   print(__name__, __package__, __path__)
   ```

3. I hope my "agressive" commenting does not violate the file's no-comment policy. ;)

Edit: After taking a look at `importlib.util.module_for_loader_wrapper` and verifying that I'm doing the `sys.modules` deletion correctly, I'm not sure if we need to set `mod.__initializing__`. It says something about "otherwise an optimization shortcut in import.c becomes wrong".

Invoking `importlib._bootstrap._call_with_frames_removed` might also be a (hacky) consideration, referring to the `importlib._bootstrap._LoaderBasics._load_module` prototype.

### Diff

```diff
--- C:\Program Files\Sublime Text 3\sublime_plugin.py  Fri Jul 10 17:40:44 2015
+++ C:\Program Files\Sublime Text 3\sublime_plugin.py  Fri Jul 17 05:24:05 2015
@@ -589,7 +589,8 @@
         self.zippath = zippath
         self.name = os.path.splitext(os.path.basename(zippath))[0]
 
-        self.contents = {"":""}
+        # Initialized for the Package's base module
+        self.contents = {"": ""}
         self.packages = {""}
 
         z = zipfile.ZipFile(zippath, 'r')
@@ -601,7 +602,7 @@
                 continue
 
             paths = base.split('/')
-            if len(paths) > 0 and paths[len(paths) - 1] == "__init__":
+            if len(paths) > 0 and paths[-1] == "__init__":
                 paths.pop()
                 self.packages.add('.'.join(paths))
 
@@ -611,6 +612,7 @@
                 print(f, "in", zippath, "is not utf-8 encoded, unable to load plugin")
                 continue
 
+            # Create empty 'parent' modules if they didn't exist
             while len(paths) > 1:
                 paths.pop()
                 parent = '.'.join(paths)
@@ -621,7 +623,7 @@
         z.close()
 
     def has(self, fullname):
-        key = '.'.join(fullname.split('.')[1:])
+        key = fullname.partition('.')[2]
         if key in self.contents:
             return True
 
@@ -635,48 +637,76 @@
 
         return False
 
-    def load_module(self, fullname):
-        if fullname in sys.modules:
-            mod = sys.modules[fullname]
-        else:
-            mod = sys.modules.setdefault(fullname, imp.new_module(fullname))
-
-        mod.__file__ = self.zippath + "/" + fullname
-        mod.__name__ = fullname
-        mod.__path__ = [self.zippath]
-        mod.__loader__ = self
-
-        key = '.'.join(fullname.split('.')[1:])
-
+    def get_source(self, fullname):
+        source, source_path, is_pkg = None, None, False
+
+        # Look for fullname in the read zipfile
+        key = fullname.partition('.')[2]
         if key in self.contents:
             source = self.contents[key]
             source_path = key + " in " + self.zippath
 
         is_pkg = key in self.packages
 
-        try:
-            override_file = os.path.join(override_path, os.sep.join(fullname.split('.')) + '.py')
-            override_package_init = os.path.join(os.path.join(override_path, os.sep.join(fullname.split('.'))), '__init__.py')
-
+        # Check if fullname has been overridden
+        override_file = os.path.join(override_path, os.sep.join(fullname.split('.')) + '.py')
+        override_package = os.path.join(override_path, os.sep.join(fullname.split('.')))
+        override_package_init = os.path.join(override_package, '__init__.py')
+
+        try:
             if os.path.isfile(override_file):
                 with open(override_file, 'r') as f:
                     source = f.read()
                     source_path = override_file
-            elif os.path.isfile(override_package_init):
-                with open(override_package_init, 'r') as f:
-                    source = f.read()
+
+            elif os.path.isdir(override_package):
+                is_pkg = True
+                if os.path.isfile(override_package_init):
                     source_path = override_package_init
-                    is_pkg = True
-        except:
-            pass
-
-        if is_pkg:
-            mod.__package__ = mod.__name__
+                    with open(override_package_init, 'r') as f:
+                        source = f.read()
+                elif source is None:
+                    # Create an empty 'parent' module
+                    source = ""
+                    source_path = override_package  # will hardly matter
+        except OSError as e:
+            raise ImportError("'%s' module could not be read: %s" % (fullname, e.args)) from None
+
+        if source is None:
+            # This can only happen if '.has' returned True earlier
+            # (which it shouldn't), but better be safe
+            raise ImportError("No module named '%s'" % fullname)
+
+        return source, source_path, is_pkg
+
+    def load_module(self, fullname):
+        if fullname in sys.modules:
+            mod = sys.modules[fullname]
+            new_mod = False
         else:
-            mod.__package__ = fullname.rpartition('.')[0]
-
-        exec(compile(source, source_path, 'exec'), mod.__dict__)
-        return mod
+            mod = sys.modules.setdefault(fullname, imp.new_module(fullname))
+            new_mod = True
+
+            mod.__file__ = self.zippath + "/" + fullname
+            mod.__name__ = fullname
+            mod.__path__ = [self.zippath]
+            mod.__loader__ = self
+
+        # Absolutely make sure to remove from sys.modules if anything fails
+        try:
+            source, source_path, is_pkg = self.get_source(fullname)
+
+            if is_pkg:
+                mod.__package__ = mod.__name__
+            else:
+                mod.__package__ = fullname.rpartition('.')[0]
+
+            exec(compile(source, source_path, 'exec'), mod.__dict__)
+            return mod
+        except:
+            if new_mod:
+                del sys.modules[fullname]
+            raise
 
 
 override_path = None
```

**Comment by FichteFoll** [comment]
Another issue with the ZipLoader is that it does not reload the actual source code when `imp.reload` is used, as mentiond here: https://github.com/wbond/package_control/commit/f155bde96b6d21c8a64ba033c434f404289908cc#diff-84e7ead640a62985b60641660e178ff7R26

**Comment by wbond** [comment]
This issue, plus a number of other small issues with the ZipLoader (including the reload issue from Package Control) should be fixed in the next dev build.

**Comment by wbond** [comment]
@FichteFoll I'm not sure what would need to find a file while it was printing an exception. The documentation says that anything can be placed in the `filename` parameter, so it should not be a problem that the format is currently custom.

Is is possible some other sort of Python was trying to use traceback info and open files using the first element in the tuple? There won't be a way to just `open()` such a filename since it is located inside of a zip file.

I did, however, fix the module `__file__` attribute so that should be more accurate, especially when an override is involved.

**Comment by FichteFoll** [comment]
@wbond the "filename" parameter is seemingly mainly used for formatting tracebacks. Imo it should be equivalent to `__file__` and not constructed like `<module.name.in.package> in <path/to/.sublime-package>`.

**Comment by FichteFoll** [comment]
*push*

The "weird" `source_path` is still present in 3112 and I haven't received a reply to this, which is why I bring it to attention again. I strongly believe that this should be equivalent to the module's `__file__`.
